### ISSUE TITLE
Buddy pounce messages are echoed back from your conversation partner

### ISSUE THREAD

**Issue by syldrathecat** [fcwill/fchat-pidgin#106]
I'm pretty sure this is caused by the same bbcode thing causing issue #99, but I'll post it separately just in case.

After a buddy pounce activates to send a queued up message to someone, it gets echoed in the conversation window back from the person it was sent to, as if they said it back to you.

![2016-03-30_19-45-32-snip](https://cloud.githubusercontent.com/assets/13056379/14138079/b51c4134-f6b2-11e5-8b88-cd03875d185f.png)

**Comment by vobe** [comment]
It is indeed due to manual printing of the BBCode in the plugin send function, and should be fixed at the same time as #99
