### ISSUE TITLE
Having multiple accounts logged in causes text to be echoed twice

### ISSUE THREAD

**Issue by vobe** [fcwill/fchat-pidgin#107]
The plugin registers one *-im-msg for every account logged, leading to duplicate messages being displayed when IMing someone

**Comment by ShadowKyogre** [comment]
I recently compiled this on Arch Linux and gave it a test run. (see https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fchat-pidgin-git for how i built it)

I'm still experiencing this bug, but it's limited to one duplicate even though I have three accounts logged in.

Can you reproduce it?

**Comment by vobe** [comment]
I don't run arch so I'm not sure what this recipe compiles exactly, can you run /version in the plugin and show us what it reports. I just tested and I don't have this bug when logging 2 different characters at the same time.

Does having only two characters logged in instead of three also exhibits the issue ?

**Comment by ShadowKyogre** [comment]
@vobe: It just compiles the plugin from the source code directly from the master branch.

Output of /version:
`You are running Pidgin F-Chat 0.5.0 (v0.5.0-129-g3fc0e11).`

That being said, the issue still happens when I just have two logged in. I disabled one of the accounts and retested sending a message.

**Comment by vobe** [comment]
It could be another issue then. Can you try running pidgin with "pidgin -c /tmp/emptyprofile" to start pidgin without any configuration, then add only one of your f-list accounts and test again ? If it works, try adding a second f-chat account.

Maybe it is something in your config, or a plugin interfering

**Comment by ShadowKyogre** [comment]
@vobe: Just did that as a test. Turns out message splitter was the one interfering (which I have set up to split some long messages since some protocols I use don't like the long messages I typed out). I was able to reproduce it with one account after I did that.

**Comment by vobe** [comment]
So this is an unrelated issue then. I have opened #110 to track it
