### ISSUE TITLE
Documentation: How to open F-chat links in Pidgin under Windows

### ISSUE THREAD

**Issue by LurkerHub** [fcwill/fchat-pidgin#190]
### Documentation: How to open F-chat links in Pidgin under Windows
**Note: this documentation is Windows-specific.**

Opening F-chat links in Pidgin (instead of in the native web-based F-chat application) is a little tricky.
To make the browser to send the links to an external application, we need to rewrite the protocol part of the url from `http:` to something else (I chose `fchat:`).

First, Install the [Redirector](https://einaregilsson.com/redirector/) add-on.

Then add a rule that rewrites the links:

![image](https://user-images.githubusercontent.com/20542915/151490740-216cb68c-4c4a-4d23-b418-87b545b931fa.png)

Or just save the following as `Redirector.json` and import it into the add-on:
```json
{
    "createdBy": "Redirector v3.5.3",
    "createdAt": "2022-01-28T04:38:10.432Z",
    "redirects": [
        {
            "description": "F-chat to pidgin",
            "exampleUrl": "http://www.f-list.net/fchat/?joinChannel=ADH-f99dbd49f94c75188c4e",
            "exampleResult": "fchat://www.f-list.net/fchat/?joinChannel=ADH-f99dbd49f94c75188c4e",
            "error": null,
            "includePattern": ".+:(//www\\.f-list\\.net/fchat/\\?joinChannel=.+)",
            "excludePattern": "",
            "patternDesc": "",
            "redirectUrl": "fchat:$1",
            "patternType": "R",
            "processMatches": "noProcessing",
            "disabled": false,
            "grouped": false,
            "appliesTo": [
                "main_frame"
            ]
        }
    ]
}
```
Next, register the protocol with Windows by saving the following as `fchat.reg` and double-clicking on it:
```reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\fchat]
@="URL:F-Chat link"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\fchat\DefaultIcon]
@="\"C:\\Program Files (x86)\\Pidgin\\pidgin.exe\",1"

[HKEY_CLASSES_ROOT\fchat\shell]
@="open"

[HKEY_CLASSES_ROOT\fchat\shell\open]

[HKEY_CLASSES_ROOT\fchat\shell\open\command]
@="\"C:\\Program Files (x86)\\Pidgin\\pidgin.exe\" --protocolhandler=%1"
```
Finally, test it by clicking on this link: http://www.f-list.net/fchat/?joinChannel=adh-9353ef5fe6b2dc7c1260
If you get a pop-up asking you to allow opening the link in Pidgin, confirm and enjoy.

**Comment by vobe** [comment]
Thanks, I have added this doc to the wiki:
https://github.com/fchat-pidgin/fchat-pidgin/wiki/Opening-F-Chat-URLs-in-Pidgin

**Comment by LurkerHub** [comment]
That link opens an empty page for me

**Comment by vobe** [comment]
check the link in the issue, I updated it

**Comment by LurkerHub** [comment]
Great!  Closing.
