### ISSUE TITLE
plugin currently gets SSL errors attempting to connect

### ISSUE THREAD

**Issue by Rakarra** [fcwill/fchat-pidgin#195]
For the past two days, the plugin has been unable to connect to f-list. The error is: "unable to connect to www.flist.net: SSL connection failed."

**Comment by vobe** [comment]
Open the "Help" menu and in the "Debug window" you'll find more information about the issue.  I can't help you without a more specific error message

**Comment by Rakarra** [comment]
Aaah! Thank you, I didn't know that was there. But that gave me enough info to fix the problem itself. Somehow pidgin lost the ability to resolve www.f-list.net entirely, despite it resolving in a web browser. A restart fixed it, which SHOULD have been my first move.
