### ISSUE TITLE
Display disconnect notification for non-friend users in private conversations

### ISSUE THREAD

**Issue by fcwill** [fcwill/fchat-pidgin#36]
When chatting with a non-friended, non-bookmarked user, you won't get a notification (e.g. _User has disconnected_) in private conversations with said user.

When the server sends FLN (User disconnected) or NLN (User connected), we should check open private conversations and display a system message.

This might have implications for privacy though? How does the web client handle this?

**Comment by Dhwty** [comment]
The web client does tell you if someone has disconnected if you're in a PM or a room with them. In fact, 2.0 distinguishes, IIRC, between 'left the room' and 'disconnected', when someone leaves a channel, just like Pidgin does. So, you're not sharing data we're not expecting to be shared.

**Comment by fcwill** [comment]
Thanks for the info! Green light for this, then.
