### ISSUE TITLE
Add missing /setmode command.

### ISSUE THREAD

**Issue by fcwill** [fcwill/fchat-pidgin#49]
/setmode changes a room's mode to accept chat, ads or both.

https://wiki.f-list.net/F-Chat_Client_Commands#RMO 
https://wiki.f-list.net/F-Chat_Server_Commands#RMO

**Comment by fcwill** [comment]
It's actually in there, somehow. There's /showads, /hideads, /showchat and /hidechat. I'll rip out the old code and rewrite this stuff, it's really weird.

**Comment by Dhwty** [comment]
I think the show/hide stuff is client-side, like the show/hide buttons on the official clients (whether or not it works...). RMO makes a server-side change to the room.
