### ISSUE TITLE
Add private conversations to the buddy list while they are open

### ISSUE THREAD

**Issue by fcwill** [fcwill/fchat-pidgin#52]
Same as for chats, we could add private conversations to a temporary group in the buddy list. This way, you can see the green/grey dot indicating a user's online status which is normally only available for friends and bookmarks.

Probably want to make this optional.

Thanks to Lutra for coming up with this :)

**Comment by vobe** [comment]
From what I found out trying to fix #36, this could also be a better way of handling it than commit ee552d7
