### ISSUE TITLE
Add callbacks for adding & removing ChanOps

### ISSUE THREAD

**Issue by fcwill** [fcwill/fchat-pidgin#54]
These callbacks are missing:

- [COA](https://wiki.f-list.net/F-Chat_Server_Commands#COA): Promote character to ChanOp
- [COR](https://wiki.f-list.net/F-Chat_Server_Commands#COR): Remove ChanOp

Both methods (COA and COR) result in the server sending the full list of ChanOps _AND_ the respective response. Anyone knows why?

**Comment by Dhwty** [comment]
Yep. Regardless of whether you're the one adding the chanop, you'll get the whole list, because the whole list is sent to _everyone in the room_, when an op gets added or removed.

**Comment by fcwill** [comment]
Makes sense, thanks!

**Comment by fcwill** [comment]
Since we don't take special actions on COA/COR we can just let COL handle everything ... closing this.
