### ISSUE TITLE
Windows installer gives no opportunity to manually specify path to pidgin directory

### ISSUE THREAD

**Issue by Jazoray** [fcwill/fchat-pidgin#60]
The fchat-pidgin installer failed for me with the error that it couldn't find the pidgin directory. reasonably, because i use a portable installation that doesn't barf in the registry. 

It is common and expected behavior for installers to let the user specify an installation path, even when the installer can determine the path on its own. In that case, the path specification dialog has a preselected path that the user can alter if desired. If a suitable path was not found, the path would be empty and the user would be prompted to enter a desired path.

if the fchat-pidgin installer could adopt this behavior i would be cheerful.

I could have manually copied the dll 20 times while i was writing this issue. What am i doing with my life.

**Comment by fcwill** [comment]
> What am i doing with my life.

You help us to improve free and open source software, that's awesome! :smiley: 

You are right, the installer is pretty dumb in its current state. We should look into fixing that and support portable  versions.
