### ISSUE TITLE
When going away and returning, status is set as "(null)" if it was previously blank.

### ISSUE THREAD

**Issue by lutramustil** [fcwill/fchat-pidgin#65]

**Comment by vobe** [comment]
Hi, can you provide more detailed steps to reproduce the problem ? I cannot seem to reproduce this using pidgin's auto away feature, or by using the right click on the tray icon. Please also provide the plugin version that you are using and your operating system

**Comment by lutramustil** [comment]
It's just the auto-idle, coming back with a blank message and in "Available" in Pidgin terms (or "online" for F-List). You can see it here: https://fstatus.stormweyr.dk/c/Lutra%20Mustil
It goes from "(null)" to "I'm not here right now". The "(null)" was supposed to be a fully blank status.

**Comment by mabes** [comment]
This is actually a global problem with the Pidgin status sync functionality. It only happens with some versions of json-glib that encode NULL pointers as the "(null)" string
