### ISSUE TITLE
Direct access to console commands?

### ISSUE THREAD

**Issue by Jazoray** [fcwill/fchat-pidgin#92]
I can use commands like /Join <channel>.

But only if i'm already in a query or channel.

is there a way to access the console directly for these commands?

**Comment by mabes** [comment]
There doesn't seem to be a way to run a command in Pidgin except from a conversation window.

**Comment by vobe** [comment]
Pidgin does not offer a way to execute commands besides the conversation window. I could not find a plugin that might help either.
