### ISSUE TITLE
Feature request: Open profile option in right click menu

### ISSUE THREAD

**Issue by Brickcaster** [fcwill/fchat-pidgin#93]
I would like the ability to see profiles quickly by right clicking a user.

Slighty related: When I view info and then click the link there, the view info window remains and leads to clutter.

**Comment by vobe** [comment]
Sadly there is nothing we can do about this. As mentionned in bug #4, pidgin doesn't allow the contextual menu to be modified in multi-user conversations. The "Info" item is the only option. We could maybe add a "Open web profile" option to contacts in the buddy list, but this is much less interesting.

**Comment by Brickcaster** [comment]
Is this a feature that can be added to Pidgin or does it go beyond that to one of the libraries it uses?  I'm not entirely familiar with what libpurple is and how it relates to Pidgin.

**Comment by vobe** [comment]
This would need some modifications in Pidgin and libpurple, but they are developped together. Libpurple is the library that handles all the low level stuff, and Pidgin is simply a graphical frontend for it.

**Comment by Brickcaster** [comment]
I didn't even think about it, but the right click-on-name menu within the chat already has "ignore" "remove friend" "remove bookmark".  This only seems to be present in the chat and not in the user list for a chat, but that's better than nothing.  Using that code could provide the desired results.

**Comment by fcwill** [comment]
This (and other modifications to the context menu) would be incredibly useful - sadly, the only interface Pidgin offers is to extend the context menu of a buddy, we can't change the menu of anyone else.
