### ISSUE TITLE
OTR shows encrypted text in the conversation window

### ISSUE THREAD

**Issue by syldrathecat** [fcwill/fchat-pidgin#99]
Attempting to use the OTR (Off-The-Record) plugin on FChat results in all of the cyper-text (beginning with ?OTR...) being shown in the conversation window.

I suspect the plugin is conflicting with OTR's attempts to hide the messages from the conversation window. Conversations start/end properly and plain-text messages still appear along with the cypher-text.

**Comment by vobe** [comment]
I have confirmed this bug, it doesn't seem to be caused by pidgin specific code, I'll look into it

**Comment by vobe** [comment]
This bug is due to BBcode parsing. The plugin decodes the BBcode input by the user before writing it into the conversation window. When using OTR, the plugin does not have access to the original message, only to the OTR ciphertext, that's why the OTR ciphertext is written in the window. We could circumvent this by adding an option not to parse outgoing BBcode

**Comment by syldrathecat** [comment]
Thanks so much for checking this out for me, I had no idea where to even start.

I think an option like that would be a bad idea (there's a lot of options already, and one like that would seem random and useless to most people).

It seems OTR sets some properties on the conversation that might be able to be inspected to detect OTR being active and avoid stepping on its feet, and/or just handling messages beginning with "?OTR" specially. Not sure if these would be considered too hacky to include, and there is some potential downside if the second is done without the first (people could hide messages from pidgin users by prefixing them with "?OTR" regardless of whether or not the OTR plugin is enabled)

I did a test with checking for the "?OTR" prefix and it got through a conversation with no spam: https://gist.github.com/syldrathecat/3b8332ca375ceca21b45 -- I might make a pull request doing the full checking which should have no user-visible negatives (except the next paragraph).

As expected, the use of OTR completely disables bbcode parsing on both ends during an OTR conversation. I'm not sure if that could be fixed without OTR providing a hook for its message writer.

This also seems to raise the question of what happens and what should happen with report chat logs when using OTR with logging disabled...

**Comment by vobe** [comment]
I'm not too fond of a solution that would be specific to OTR, we should try to find a way that works with any plugin that modifies outgoing text some way or another. I'll try to see if we can use signals for this somehow. Or GUI specific code. You're right there are too many options already.

As for chat reports, seems to me like OTR disables logging to make sure a conversation never "leaks" out of the conversation window, and perhaps we should respect that. It's a philosphical question ;)

**Comment by vobe** [comment]
Found some sort of a fix by patching Pidgin 
```
--- a/libpurple/plugins/ssl/ssl-nss.c
+++ b/libpurple/plugins/ssl/ssl-nss.c
@@ -544,8 +544,10 @@ ssl_nss_connect(PurpleSslConnection *gsc)
        if (gsc->verifier != NULL)
                SSL_AuthCertificateHook(nss_data->in, ssl_auth_cert, NULL);
 
-       if(gsc->host)
+       if(gsc->host) {
                SSL_SetURL(nss_data->in, gsc->host);
+               SSL_SetSockPeerID(nss_data->in, gsc->host);
+       }
 
 #if 0
        /* This seems like it'd the be the correct way to implement the
```

It seems to work so far (but we should probably include the port too, as the doc says). Also, it might be worth reporting to CloudFlare before sending a bug report to pidgin .
